 CREATE TABLE IF NOT EXISTS ranks(
 	rank_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 	rank_name VARCHAR(30) NOT NULL,
 	rank_value INT NOT NULL
 );
 
  CREATE TABLE IF NOT EXISTS users(
 	user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 	username VARCHAR(30) NOT NULL,
 	email VARCHAR(50) NOT NULL,
 	password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 	rank_id INT NOT NULL,
 	FOREIGN KEY (rank_id) REFERENCES ranks(rank_id)
 );

CREATE TABLE IF NOT EXISTS board (
	post_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,  
    rank_id INT NOT NULL,
    content VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (rank_id) REFERENCES ranks(rank_id)
 );
 

 
